# Generated by Django 5.2.5 on 2025-11-12 02:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameHistory',
            fields=[
                ('match_id', models.UUIDField(editable=False, help_text='UUID generated by frontend', primary_key=True, serialize=False, unique=True)),
                ('game_type', models.CharField(choices=[('solo', 'Solo'), ('multiplayer', 'Multiplayer')], max_length=20)),
                ('game_mode', models.CharField(choices=[('timed', 'Timed'), ('untimed', 'Untimed')], max_length=20)),
                ('operation', models.CharField(choices=[('addition', 'Addition'), ('subtraction', 'Subtraction')], max_length=20)),
                ('grid_size', models.PositiveSmallIntegerField()),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('abandoned', 'Abandoned'), ('timed_out', 'Timed Out')], max_length=20)),
                ('final_score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('accuracy_percentage', models.FloatField(help_text='correct_cells / total_player_cells * 100', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('hints_used', models.PositiveSmallIntegerField(default=0)),
                ('completion_time', models.PositiveIntegerField(blank=True, help_text='Seconds to complete – required only for timed mode', null=True)),
                ('room_code', models.CharField(blank=True, db_index=True, help_text='6-char room code – NULL for solo', max_length=6, null=True)),
                ('position', models.PositiveSmallIntegerField(blank=True, help_text='Player rank – NULL for solo', null=True)),
                ('total_players', models.PositiveSmallIntegerField(blank=True, help_text='Number of players in room – NULL for solo', null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Game History',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['player', '-timestamp'], name='game_gamehi_player__077284_idx'), models.Index(fields=['-timestamp'], name='game_gamehi_timesta_38a815_idx'), models.Index(fields=['room_code', '-timestamp'], name='game_gamehi_room_co_400817_idx')],
                'constraints': [models.UniqueConstraint(fields=('match_id',), name='unique_match_id')],
            },
        ),
    ]
