# Generated by Django 5.2.5 on 2025-11-12 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamehistory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='gamehistory',
            name='match_id',
            field=models.CharField(db_index=True, max_length=36, unique=True),
        ),
    ]
