# Generated by Django 5.2.5 on 2025-11-12 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_gamehistory_id_alter_gamehistory_match_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamehistory',
            name='points_earned',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Points calculated from accuracy, hints, time, position'),
        ),
    ]
