from django.shortcuts import render


# DOWNLOAD PAGE THAT WILL HAVE A LINKS TO DOWNLOAD THE GAME ON APPLE STORE AND GOOGLE PLAY STORE.
# THIS WILL BE A SIMPLE HTML PAGE RENDERED USING DJANGO TEMPLATES.
# THE DOWNLOAD BUTTON WILL SAVE THE USERS-REFERRAL CODE AND IP OF THE USER FOR TRACKING PURPOSES.
#