# Generated by Django 5.2.5 on 2025-10-07 02:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userwallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwallet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userwallet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
