# Generated by Django 5.2.5 on 2025-11-11 21:23

import django.db.models.deletion
import django_resized.forms
import src.services.user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userwallet',
            name='available_coins',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='referral_code',
            field=models.CharField(blank=True, max_length=8, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='user.userprofile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_referrals',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=True, null=True, quality=85, scale=None, size=[300, 300], upload_to=src.services.user.models.user_avatar_path),
        ),
        migrations.AlterField(
            model_name='userwallet',
            name='total_coins',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userwallet',
            name='used_coins',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
