# Generated by Django 5.2.5 on 2025-11-12 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_userwallet_available_coins_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='total_game_points',
            field=models.PositiveBigIntegerField(db_index=True, default=0, help_text='Total points earned from completed games'),
        ),
    ]
